quest = input('Digite algo: ')
print('{} é um valor {}'.format(quest, type(quest)))
print('{} é Letra? {}'.format(quest, quest.isalpha()))
print('{} é número? {}'.format(quest, quest.isnumeric()))
print('{} é um valor alfanumerico? {}'.format(quest, quest.isalnum()))
print('{} é todo maiusculo? {}, é todo minusculo? {}'.format(quest, quest.isupper(),quest.islower()))
print('{} é decimal? {}'.format(quest, quest.isdecimal()))
print('{} é printável? {}'.format(quest, quest.isprintable()))
print(f'A {quest} é uma letra {quest.isalpha()}? e pode ser um número {quest.isnumeric()}')